[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "my_plugin1"
version = "1.0"
description = "desc1"

[project.entry-points.cogent3_plugins]
myplugin = "my_plugin1:myfunc1"