[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "my_plugin2"
version = "1.0"
description = "desc2"

[project.entry-points."cogent3_plugins.database"]
myplugin2 = "my_plugin2:myfunc2"