[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "my_plugin5"
version = "1.0"
description = "desc5"

[project.entry-points.database_plugins]
myplugin = "my_plugin5:myfunc5"